using System.Diagnostics.Contracts;

namespace Ecommerce_API_Project.Models
{
        public class User
        {
            //Create Uniqueness ID + Autogenerated
            public Guid UserId { get; set; } = Guid.NewGuid();
            public string UserName { get; set; } = string.Empty;
            public string Email { get; set; } = string.Empty;

            // optional means add or not add value + custom validate password
            public string? Password { get; set; }
            public string? Role { get; set; } = "user";
            public bool? IsActive { get; set; } = true;
            public List<Cart> Carts { get; set; } // Navigation property
    }
}

